---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-example-com
  namespace: default # This namespace should be the same as where the service runs
spec:
  secretName: local-example-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.example.com"
  dnsNames:
    - "local.example.com"
    - "*.local.example.com"
