globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"
  - "--entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8,192.168.0.0/16,10.50.5.31/16"
    

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=DEBUG"

deployment:
  enabled: true
  replicas: 1
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true
  plex:
    port: 32400
    expose: true
    exposedPort: 32400
    protocol: TCP
      
ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    metallb.universe.tf/loadBalancerIPs: 10.20.10.10 # this should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []
  externalTrafficPolicy: Local

logs:
  access:
    enabled: true


# --entryPoints.websecure.forwardedHeaders.trustedIPs=10.0.0.0/8,192.168.0.0/16