# Default headers that are often used
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: default
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
---
# # Default headers that are often used
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: default-headers
#   namespace: media
# spec:
#   headers:
#     browserXssFilter: true
#     contentTypeNosniff: true
#     forceSTSHeader: true
#     stsIncludeSubdomains: true
#     stsPreload: true
#     stsSeconds: 15552000
#     customFrameOptionsValue: SAMEORIGIN
#     customRequestHeaders:
#       X-Forwarded-Proto: https
# ---
# # Allow nginx ip's
# apiVersion: traefik.containo.us/v1alpha1
# kind: MiddlewareTCP
# metadata:
#   name: nginx-tcp-headers
#   namespace: default
# spec:
#   ipWhiteList:
#     sourceRange:
#       - 10.50.5.30
#       - 10.50.5.31
#       - 10.50.5.32
