---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: media
  labels:
    app: nzbget
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
      - name: nzbget
        image: linuxserver/nzbget:21.1.20221201
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Europe/Helsinki
        - name: PUID
          value: "1037"
        - name: PGID
          value: "100"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 6789
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1  
        volumeMounts:
        - name: nzbget-config
          mountPath: /config         
        - name: nzbget-downloads
          mountPath: /downloads
        - name: nzbget-scripts
          mountPath: /script/
      volumes:
      - name: nzbget-downloads
        nfs:
          path: /volume1/downloads
          server: 10.20.0.5
      - name: nzbget-scripts
        nfs:
          path: /volume1/k8s-media/
          server: 10.20.0.5
      - name: nzbget-config
        persistentVolumeClaim:
          claimName: nzbget-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nzbget
  namespace: media
spec:
  selector:
    app: nzbget
  ports:
  - name: http
    targetPort: 6789
    port: 6789