---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels:
    app: radarr
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:5.3.6
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Europe/Helsinki
        - name: PUID
          value: "1037"
        - name: PGID
          value: "100"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /system/status
            port: 7878
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1  
        volumeMounts:
        - name: radarr-config
          mountPath: /config         
        - name: radarr-media-movies
          mountPath: /movies
        - name: radarr-downloads
          mountPath: /downloads
      volumes:
      - name: radarr-media-movies
        nfs:
          path: /volume1/media/Movies
          server: 10.20.0.5
      - name: radarr-downloads
        nfs:
          path: /volume1/downloads
          server: 10.20.0.5
      - name: radarr-config
        persistentVolumeClaim:
          claimName: radarr-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  selector:
    app: radarr
  ports:
  - name: http
    targetPort: 7878
    port: 7878