---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media
  labels:
    app: sabnzbd
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: linuxserver/sabnzbd:4.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Europe/Helsinki
        - name: PUID
          value: "1037"
        - name: PGID
          value: "100"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1  
        volumeMounts:
        - name: sabnzbd-config
          mountPath: /config         
        - name: sabnzbd-downloads
          mountPath: /downloads
        - name: sabnzbd-scripts
          mountPath: /script/
      volumes:
      - name: sabnzbd-downloads
        nfs:
          path: /volume1/downloads
          server: 10.20.0.5
      - name: sabnzbd-scripts
        nfs:
          path: /volume1/k8s-media/
          server: 10.20.0.5
      - name: sabnzbd-config
        persistentVolumeClaim:
          claimName: sabnzbd-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: media
spec:
  selector:
    app: sabnzbd
  ports:
  - name: http
    targetPort: 8080
    port: 8080