---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr:3.0.10
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Europe/Helsinki
        - name: PUID
          value: "1037"
        - name: PGID
          value: "100"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /system/status
            port: 8989
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1  
        volumeMounts:
        - name: sonarr-config
          mountPath: /config         
        - name: sonarr-media-tv
          mountPath: /tv
        - name: sonarr-downloads
          mountPath: /downloads
      volumes:
      - name: sonarr-media-tv
        nfs:
          path: /volume1/media/TV
          server: 10.20.0.5
      - name: sonarr-downloads
        nfs:
          path: /volume1/downloads
          server: 10.20.0.5
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
spec:
  selector:
    app: sonarr
  ports:
  - name: http
    targetPort: 8989
    port: 8989
