apiVersion: v1
data:
  rclone.conf: >-
    ICBbY3ViZV0KICB0eXBlID0gc21iCiAgaG9zdCA9IDEwLjIwLjAuNQogIHVzZXIgPSBtZWRpYQogIHBhc3MgPSBRVEdIZzNPaFlpdGcyQjNJbjZ1d0ZXUUxPY1JFS1FNbk5VUG13RHdZVmNoWk9xakl0MXNJTWQ4eExkOEFwMUEKICBzcG4gPSBwbGV4LWt1YmU=
kind: Secret
metadata:
  name: plex-rclone
  namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi